name: Deploy
on:
  push:
    branches: [main]
    paths:
      - 'web/**'
      
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build step
        working-directory: ./web
        run: "deno task build" # 📝 Update the build command(s) if necessary

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          root: web # 📝 Update the root directory if necessary
          project: "insta-dupe" # 📝 Update the deploy project name if necessary
          entrypoint: "./src/main.ts" # 📝 Update the entrypoint if necessary
